### ISSUE TITLE
Flush throws 406 Not Acceptable

### ISSUE THREAD

**Issue by FedTro** [jprante/log4j2-elasticsearch-http#5]
I came across with the issue. Method flush of ElasticsearchHttpClient class throws the exception "no OK response: 406 Not Acceptable org.apache.logging.log4j.core.appender.AppenderLoggingException".
I found out that log data are flushed by a http request with **content-type "application/x-www-form-urlencoded"**. But according to last [ElasticSearch API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html) content-type header must have the value **"application/x-ndjson"**.

> NOTE: the final line of data must end with a newline character \n. Each newline character may be preceded by a carriage return \r. When sending requests to this endpoint the Content-Type header should be set to application/x-ndjson

The issue can be resolved by adding a row 
`connection.setRequestProperty("Content-Type", "application/x-ndjson");`
into ElasticsearchHttpClient.flush method.

**Comment by jprante** [comment]
Thanks for the hint.
